### ISSUE TITLE
select count of words in HTMH

### ISSUE THREAD

**Issue by MostafaRahgouy** [Rahgooy/author_masking#4]
as you know in the code we select one word in each sentence for a change.
the question is what is an effect if we select one more word in each sentence for changing?
we work on this effect

**Comment by Rahgooy** [comment]
I think you did some experiments about this, right? if yes, could you please add the conclusion here and close this issue?

**Comment by MostafaRahgouy** [comment]
yes, of course, we do it very soon

**Comment by HamedBabaei** [comment]
Conclusion of Experiments:
1-for first: no changing at original file
When we don't change any word at sentence, actually we provide the original document of author for glad
to verify them, the result of experiment are in bellow:
Whole test document: 125
accuracy of glad: 70.39999
TP : 88
FN : 37
Uknown document: 0

2-for second time: changing one word in each sentence
the result of experiment are in bellow:
Whole test document: 125
accuracy of glad: 67.5
TP : 81
FN : 39
Uknown document: 5

3-for third time: changing two word in each sentence
the result of experiment are in bellow:
Whole test document: 125
accuracy of glad: 68.03278
TP : 83
FN : 39
Uknown document: 3

4-for fourth time: changing three word in each sentence
the result of experiment are in bellow:
Whole test document: 125
accuracy of glad: 68.54838
TP : 85
FN : 39
Uknown document: 1

and the some document score in each 4 experiment are in bellow:
document	experiment-1 	experiment-2 	experiment-3 	experiment-4
-------------------------------------------------------------------------
EN002		0.578119		0.587533		0.601934		0.607713
EN049		0.750502		0.765853		0.769499		0.772369
EN043		0.678289		0.707343		0.702094		0.703485

EN005		0.638868		0.590902		0.565038		0.596573
EN013		0.552411		0.500000		0.481778		0.510581
EN018		0.554868		0.500000		0.500000		0.518794
EN034		0.774262		0.575810		0.563702		0.599550
EN023		0.765728		0.719184		0.712825		0.704089

EN053		0.864960		0.690633		0.670717		0.607029
EN054		0.893371		0.569692		0.568842		0.578069

**Comment by Rahgooy** [comment]
It is strange that by increasing the number of changes per sentence, "glad" improves!

**Comment by MostafaRahgouy** [comment]
yes it's so strange
